---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
#  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
#  - ./thanos/ks.yaml
  - ./speedtest-exporter/ks.yaml
  - ./loki/ks.yaml
  - ./unpoller/ks.yaml

